# Generated by Django 3.1.1 on 2021-01-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainer_name', models.CharField(max_length=50)),
                ('complainer_email', models.EmailField(max_length=255)),
                ('complainer_phone_number', models.CharField(max_length=15)),
                ('complaint_address', models.TextField()),
                ('complaint_postal_code', models.CharField(max_length=20)),
                ('complain_subject', models.CharField(max_length=100)),
                ('complain', models.TextField()),
                ('image_field', models.ImageField(default='files/icon.png', upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
