# Generated by Django 3.1.1 on 2021-01-28 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain_table',
            name='image_field',
            field=models.ImageField(default='files/logo512.png', upload_to='files/'),
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree', models.IntegerField()),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain.complain_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
