# Generated by Django 3.1.1 on 2021-02-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0008_complain_table_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain_table',
            name='user',
        ),
    ]
