version: '3.7'

services:
  django_gunicorn_nginx:
    volumes:
      - static:/static
    #env_file:
      #- .env
    build:
      context: .
    ports:
      - "5000:5000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn_nginx

volumes:
  static: